#!/usr/bin/env python3
"""Generate watchlist_names.txt from the stockticker watchlist.

ytwatcher's match_watchlist matches whole words, which works for ticker
symbols — but news titles usually say the company name ("Microsoft"),
not the ticker ("MSFT"). This script resolves each ticker in
watchlist.txt to its company name via the stockticker fundamentals db
and writes the names to watchlist_names.txt (same directory), which
subscriptions.yaml lists as a second match_watchlist file.

Re-run when watchlist.txt changes (ytwatcher re-reads the file on its
next scan round once it changes). Idempotent.
"""

import sqlite3
import sys
from pathlib import Path

STOCKTICKER = Path("/home/justin/Projects/stockticker")
WATCHLIST = STOCKTICKER / "watchlist.txt"
NAMES_OUT = STOCKTICKER / "watchlist_names.txt"
DB = STOCKTICKER / "data" / "fundamentals.db"

# Trailing legal-form words to strip so titles match the short name
# ("NVIDIA Corporation" -> "NVIDIA"). Multi-word forms first.
SUFFIXES = [
    "Class A", "Class B", "Class C", "Common Stock", "Sponsored ADR",
    "Inc.", "Inc", "Corp.", "Corp", "Corporation", "Ltd.", "Ltd",
    "Limited", "PLC", "N.V.", "NV", "S.A.", "SA", "AG", "SE", "ASA",
    "Co.", "Co", "Company", "Holdings", "Holding", "Group", "ADR",
]


# Well-known aliases and former names that news titles use instead of the
# official company name ("Google" for Alphabet, "Facebook" for Meta, ...).
# Keyed by ticker; extend as needed.
ALIASES = {
    "GOOG": ["Google"],
    "GOOGL": ["Google"],
    "META": ["Meta", "Facebook"],
    "TSM": ["TSMC"],
    "MU": ["Micron"],
    "PDD": ["Pinduoduo", "Temu"],
}


def clean_name(name):
    """Strip corporate suffixes; return the shorter form (or the original)."""
    short = name.strip()
    changed = True
    while changed:
        changed = False
        for suffix in SUFFIXES:
            if short.lower().endswith(suffix.lower()):
                short = short[: -len(suffix)].rstrip(" ,.&")
                changed = True
    # Share-class markers, e.g. "Alphabet-C" -> "Alphabet".
    if len(short) > 3 and short[-2] == "-" and short[-1] in "ABC":
        short = short[:-2]
    return short or name.strip()


def main():
    tickers = []
    for line in WATCHLIST.read_text().splitlines():
        ticker = line.strip()
        if ticker and not ticker.startswith("#"):
            tickers.append(ticker)

    con = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    profiles = dict(con.execute("SELECT ticker, name FROM company_profiles"))

    lines = [
        "# Generated by update_watchlist_names.py - do not edit by hand.",
        "# Re-run it when watchlist.txt changes.",
    ]
    missing = []
    for ticker in tickers:
        name = profiles.get(ticker) or profiles.get(ticker.lstrip("^"))
        if not name:
            missing.append(ticker)
            continue
        lines.append(f"# {ticker}")
        keywords = [name.strip(), clean_name(name), *ALIASES.get(ticker, [])]
        seen = set()
        for keyword in keywords:
            if keyword and keyword.lower() not in seen:
                seen.add(keyword.lower())
                lines.append(keyword)

    NAMES_OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {NAMES_OUT}: {len(tickers) - len(missing)}/{len(tickers)} names")
    if missing:
        print("no company profile for: " + ", ".join(missing))


if __name__ == "__main__":
    sys.exit(main())
